pipeline {
    agent {
        docker { image 'maven:3.6.3' }
    }
    stages {
        stage('Build') {
            steps {
                //运行构建
                sh "mvn compile"
            }
        }
        stage('Test') {
            steps {
                //测试
                sh "echo 'Test'"
            }
        }
        stage('Push') {
            steps {
                //发布上线
                sh "echo Push"
            }
        }
    }
}