pipeline {
    agent {label 'master'}
    stages {
        stage('Build') {
            steps {
                //运行构建
                bat "echo 'Build'"
            }
        }
        stage('Test') {
            steps {
                //测试
                bat "echo 'Test'"
            }
        }
        stage('Push') {
            steps {
                //发布上线
                bat "echo Push"
            }
        }
    }
}